//
// CoverageExcludeAttribute.cs
//
// Product: Total Payment Platform
//
// Component: McKesson.TPP.SDK.Common
//
// Description: Indicates that a code coverage tool should ignore the element
//              to which this attribute is attached.
// 
//
// Author: Scott Lurowist
//
// Copyright © 2012 McKesson Corporation and/or one of its subsidiaries.  
// All rights reserved. Use of this software is governed by a license agreement. This 
// software contains confidential, proprietary and trade secret information of McKesson 
// Corporation and/or one of its subsidiaries and is protected under United States and 
// international copyright and other intellectual property laws.
//




using System;





/// <summary>
/// Reasons used to exclude code from a coveage tool.
/// </summary>
public enum ExclusionReason
{

    /// <summary>
    /// The code contains mostly .NET Framework code such as configuration
    /// elements. Framework code is tested by Microsoft.
    /// </summary>
    FrameworkCode,

    /// <summary>
    /// The code is generated by a tool and does not need to be tested.
    /// </summary>
    GeneratedCode,

    /// <summary>
    /// The code is not used in a production scenario and does not need 
    /// to be tested. The code should be reviewed and possibly removed.
    /// </summary>
    NonProductionScenario,

    /// <summary>
    /// The code is to be excluded for the reason in the reason explanation.
    /// </summary>
    /// <remarks>
    /// When using this reason, be sure to give a detailed explanation.
    /// </remarks>
    Other,

    /// <summary>
    /// The code is used in testing and does not need to be tested.
    /// </summary>
    TestCode,

    /// <summary>
    /// The code is third party code and is not tested.
    /// </summary>
    ThirdPartyCode
}


/// <summary>
/// Indicates that a code coverage tool should ignore the element to which
/// this attribute is attached.
/// </summary>
/// <remarks>
/// This attribute must be defined outside any namespace. If it is defined in
/// within a namespace then it will not work!
/// </remarks>
[AttributeUsage(AttributeTargets.All)]
public class CoverageExcludeAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of the CoverageExcludeAttribute with 
    /// the reason why coverage is bing excluded.
    /// </summary>
    /// <param name="reason">
    /// The reason the code is being excluded from testing.
    /// </param>
    public CoverageExcludeAttribute(ExclusionReason reason)
    {
    }


    /// <summary>
    /// Gets or sets a detailed developer reason for code exclusion.
    /// </summary>
    public string ExclusionReasonDescription { get; set; }
}